instance:
  company_name: JJGDevelopment
  hostname: my-machine

influxdb:
  host: 127.0.0.1
  port: 8086
  user: my-user
  password: secretpassword
  database: monitoring

# Criticality: 1 (send email) or 0 (doesn't send email)
services:
  - name: cups
    criticality: 0
    log_file: /path/to/file.log
  - name: sshd
    criticality: 1
    log_file: /path/to/file.log
  - name: telnet
    criticality: 1
    log_file: /path/to/file.log

docker:
  - name: hello-world
    criticality: 1

email:
  sender: monitoring@mycompany.com
  receiver: team_monitoring@mycompany.com
  smtp_server: smtp.gmail.com
  smtp_port: 465
  password: MyTeamMonitoring
  subject: "Service down"